version: '2'
services:
  node:
    build: .
    container_name: node
    environment:
      SERVER_PORT: 3000
      REDIS_URL: "redis://redis:6379"
    ports: 
      - "3000:3000"
    links:
      - redis
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"